/**
 * Error Codes for i18n Support
 *
 * These codes are used across the backend to identify specific errors.
 * The frontend will translate these codes to user-friendly messages
 * based on the user's language preference.
 */

export const ErrorCodes = {
  // Authentication Errors
  AUTH_USER_EXISTS: 'AUTH_USER_EXISTS',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_NO_TOKEN: 'AUTH_NO_TOKEN',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  AUTH_EMAIL_REQUIRED: 'AUTH_EMAIL_REQUIRED',
  AUTH_PASSWORD_REQUIRED: 'AUTH_PASSWORD_REQUIRED',

  // Account Errors
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_INSUFFICIENT_BALANCE: 'ACCOUNT_INSUFFICIENT_BALANCE',
  ACCOUNT_ARCHIVED: 'ACCOUNT_ARCHIVED',
  ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
  ACCOUNT_INVALID_TYPE: 'ACCOUNT_INVALID_TYPE',
  ACCOUNT_DELETE_DEFAULT: 'ACCOUNT_DELETE_DEFAULT',

  // Transaction Errors
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_INVALID_ACCOUNT: 'TRANSACTION_INVALID_ACCOUNT',
  TRANSACTION_INVALID_AMOUNT: 'TRANSACTION_INVALID_AMOUNT',
  TRANSACTION_INVALID_TYPE: 'TRANSACTION_INVALID_TYPE',
  TRANSACTION_INVALID_DATE: 'TRANSACTION_INVALID_DATE',
  TRANSACTION_SAME_ACCOUNT_TRANSFER: 'TRANSACTION_SAME_ACCOUNT_TRANSFER',

  // Category Errors
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_SYSTEM_CANNOT_DELETE: 'CATEGORY_SYSTEM_CANNOT_DELETE',
  CATEGORY_IN_USE: 'CATEGORY_IN_USE',

  // Group Errors
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  GROUP_UNAUTHORIZED: 'GROUP_UNAUTHORIZED',
  GROUP_ALREADY_MEMBER: 'GROUP_ALREADY_MEMBER',
  GROUP_NOT_MEMBER: 'GROUP_NOT_MEMBER',
  GROUP_CREATOR_CANNOT_LEAVE: 'GROUP_CREATOR_CANNOT_LEAVE',
  GROUP_INVALID_SPLIT_TYPE: 'GROUP_INVALID_SPLIT_TYPE',
  GROUP_SPLIT_TOTAL_INVALID: 'GROUP_SPLIT_TOTAL_INVALID',

  // Shared Expense Errors
  SHARED_EXPENSE_NOT_FOUND: 'SHARED_EXPENSE_NOT_FOUND',
  SHARED_EXPENSE_UNAUTHORIZED: 'SHARED_EXPENSE_UNAUTHORIZED',
  SHARED_EXPENSE_INVALID_PARTICIPANTS: 'SHARED_EXPENSE_INVALID_PARTICIPANTS',
  SHARED_EXPENSE_ALREADY_PAID: 'SHARED_EXPENSE_ALREADY_PAID',
  SHARED_EXPENSE_NOT_MEMBER: 'SHARED_EXPENSE_NOT_MEMBER',
  SHARED_EXPENSE_PARTICIPANTS_NOT_MEMBERS: 'SHARED_EXPENSE_PARTICIPANTS_NOT_MEMBERS',
  SHARED_EXPENSE_PERCENTAGE_INVALID: 'SHARED_EXPENSE_PERCENTAGE_INVALID',
  SHARED_EXPENSE_EXACT_AMOUNT_INVALID: 'SHARED_EXPENSE_EXACT_AMOUNT_INVALID',
  SHARED_EXPENSE_ONLY_PAYER_CAN_UPDATE: 'SHARED_EXPENSE_ONLY_PAYER_CAN_UPDATE',
  SHARED_EXPENSE_ONLY_PAYER_CAN_DELETE: 'SHARED_EXPENSE_ONLY_PAYER_CAN_DELETE',
  SHARED_EXPENSE_PARTICIPANT_NOT_FOUND: 'SHARED_EXPENSE_PARTICIPANT_NOT_FOUND',
  SHARED_EXPENSE_INVALID_PAYMENT_PERMISSION: 'SHARED_EXPENSE_INVALID_PAYMENT_PERMISSION',
  SHARED_EXPENSE_ONLY_PAYER_CAN_UNDO: 'SHARED_EXPENSE_ONLY_PAYER_CAN_UNDO',
  SHARED_EXPENSE_NO_BALANCE: 'SHARED_EXPENSE_NO_BALANCE',
  SHARED_EXPENSE_USERS_NOT_IN_GROUP: 'SHARED_EXPENSE_USERS_NOT_IN_GROUP',

  // Loan Errors
  LOAN_NOT_FOUND: 'LOAN_NOT_FOUND',
  LOAN_UNAUTHORIZED: 'LOAN_UNAUTHORIZED',
  LOAN_ALREADY_PAID: 'LOAN_ALREADY_PAID',
  LOAN_INVALID_AMOUNT: 'LOAN_INVALID_AMOUNT',
  LOAN_PAYMENT_EXCEEDS_REMAINING: 'LOAN_PAYMENT_EXCEEDS_REMAINING',

  // Budget Errors
  BUDGET_NOT_FOUND: 'BUDGET_NOT_FOUND',
  BUDGET_ALREADY_EXISTS: 'BUDGET_ALREADY_EXISTS',
  BUDGET_INVALID_PERIOD: 'BUDGET_INVALID_PERIOD',

  // Tag Errors
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  TAG_ALREADY_EXISTS: 'TAG_ALREADY_EXISTS',
  TAG_IN_USE: 'TAG_IN_USE',

  // Import Errors
  IMPORT_NOT_FOUND: 'IMPORT_NOT_FOUND',
  IMPORT_INVALID_FILE: 'IMPORT_INVALID_FILE',
  IMPORT_INVALID_FORMAT: 'IMPORT_INVALID_FORMAT',
  IMPORT_FILE_TOO_LARGE: 'IMPORT_FILE_TOO_LARGE',
  IMPORT_PROCESSING: 'IMPORT_PROCESSING',

  // Notification Errors
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_UNAUTHORIZED: 'NOTIFICATION_UNAUTHORIZED',

  // Investment Errors
  INVESTMENT_NOT_FOUND: 'INVESTMENT_NOT_FOUND',
  INVESTMENT_UNAUTHORIZED: 'INVESTMENT_UNAUTHORIZED',
  INVESTMENT_INSUFFICIENT_QUANTITY: 'INVESTMENT_INSUFFICIENT_QUANTITY',
  INVESTMENT_INVALID_PRICE: 'INVESTMENT_INVALID_PRICE',
  INVESTMENT_INVALID_QUANTITY: 'INVESTMENT_INVALID_QUANTITY',
  INVESTMENT_PRICE_NOT_AVAILABLE: 'INVESTMENT_PRICE_NOT_AVAILABLE',

  // General Errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  INVALID_INPUT: 'INVALID_INPUT',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
